### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by fhzyfjy** [xyuanmu/dig#1]
按你说的方法一：到 Best DNS 首页 Where do you need a DNS from? 下方选一个地区的网址进行复制。
运行 debug.bat，右键，粘贴网址，按下回车，之后会自动获取网页内的IP并使用dig工具获取返回的IP段。无法运行。截图见附件。不知什么原因。谢谢
![2016-03-06_144423](https://cloud.githubusercontent.com/assets/11030827/13552745/5cd653f4-e3aa-11e5-96f9-04840a47eb0d.jpg)

**Comment by xyuanmu** [comment]
你路径应该是有空格，已经修复，重新下载 [debug.bat](https://raw.githubusercontent.com/xyuanmu/dig/master/debug.bat) 文件替换即可。

**Comment by fhzyfjy** [comment]
非常感谢，问题已解决。另外，运行 debug.bat后得到的ip.txt，下步如何做？我进入dig-64bit文件夹运行check.bat，显示“input ip ;"。我把ip.txt中的ip全选但只能copy一个ip，且运行后没什么结果。我是小白，烦请赐教。谢谢
