### ISSUE TITLE
ip.txt格式转换问题

### ISSUE THREAD

**Issue by fhzyfjy** [xyuanmu/dig#2]
运行 debug.bat后得到的ip.txt，下步如何做？我进入dig-64bit文件夹运行check.bat，显示“input ip ;"。我把ip.txt中的ip全选但只能copy一个ip，且运行后没什么结果。我是小白，烦请赐教。谢谢

**Comment by xyuanmu** [comment]
获得ip.txt后没有自动开始dig IP吗？
![dig](https://cloud.githubusercontent.com/assets/12442896/13554434/bdbc15f4-e3e2-11e5-892d-6623a636160e.png)

**Comment by fhzyfjy** [comment]
自动了。如你截图红框所示。但我没有等全部结束就退出了。是不是这个缘故？谢谢

**Comment by xyuanmu** [comment]
一个页面有100个IP，10分钟左右就能dig完，结束以后会自动提取日志中的IP段生成ip_range.txt的。如果中途退出，重新运行 debug.bat，输入1，因为没记录位置所以会从头开始dig。

**Comment by fhzyfjy** [comment]
谢谢。我刚试了，成功了。但ip_range 产生的ip放到哪里？
1、是放到dig-64bit文件夹？之后运行check.bat？txt文件名字是否要改？还是不变，仍为ip_range；或
2、你写的另外一个软件checkiptools-master中的googleip.txt中？
请教，你为何写两个软件checkiptools-master 和dig-master ？这两个软件中都有checkip.bat。谢谢
