### ISSUE TITLE
ip_range 产生的ip放到哪里？

### ISSUE THREAD

**Issue by fhzyfjy** [xyuanmu/dig#3]
请教大侠：ip_range 产生的ip
1、是放到dig-64bit文件夹？之后运行check.bat？txt文件名字是否要改？还是不变，仍为ip_range；或
2、你写的另外一个软件checkiptools-master中的googleip.txt中？
请教，你为何写两个软件checkiptools-master 和dig-master ？这两个软件中都有checkip.bat。谢谢

**Comment by xyuanmu** [comment]
你没看使用说明吗？
生成 ip_range.txt 后将里面的IP段导入扫描工具如 checkiptools 进行扫描和管理。
还有，只有 checkiptools 里有 checkip.bat 好不啦

**Comment by fhzyfjy** [comment]
多谢大侠。我是小白，看了几遍都没太搞懂。烦请指点。是吧ip_range.txt 里面的IP段导入到ip_range_origin.txt吗？跪谢

**Comment by xyuanmu** [comment]
是的，然后运行一遍 iptools，输入4，会自动整理IP段并去掉无用的IP，然后用 checkip 扫描出可用IP即可。当然日本IP基本都被封完，估计找不到多少能用的了。

**Comment by fhzyfjy** [comment]
跪谢、跪谢。祝好祝好
